@startmindmap

*[#Gray] Aplicativo 
**[#LightBlue]  Cadastrar
***[#Cyan] Inserir endereço 
***[#Cyan] Inserir meio de pagamento
***[#Cyan] Inserir dado para contato

**[#LightBlue] Fazer Pedido
***[#Cyan] Escolher pedido
***[#Cyan] Buscar dados do cadastro
**[#LightBlue] Buscar categorias
**[#LightBlue] Acessar Histórico
***[#Cyan] Refazer pedido
**[#LightBlue] Notificar Pedido



'--[#LightBlue] 2°
'---[#Red] 3°



@endmindmap
