# Generated by Django 5.2.1 on 2025-05-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simblissimaApp", "0002_cliente_pedido_itempedido_statuspedido"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Produto",
        ),
    ]
